/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./main.jsx",
    "./App.jsx",
    "./pages/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./data/**/*.{js,jsx,ts,tsx}",
    "./lib/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'Roboto', 'system-ui', 'sans-serif'],
      },
      colors: {
        background: "#f8fafc",
        foreground: "#1e293b",
        card: "#ffffff",
        "card-foreground": "#1e293b",
        primary: "#3b82f6",
        "primary-foreground": "#ffffff",
        secondary: "#e2e8f0",
        "secondary-foreground": "#334155",
        muted: "#f1f5f9",
        "muted-foreground": "#64748b",
        accent: "#e0e7ff",
        "accent-foreground": "#334155",
        destructive: "#ef4444",
        "destructive-foreground": "#ffffff",
        border: "#e2e8f0",
        input: "#e2e8f0",
        ring: "#3b82f6",
        success: "#22c55e",
        "success-foreground": "#ffffff",
        warning: "#f59e0b",
        "warning-foreground": "#422006",
        sidebar: "#ffffff",
        "sidebar-foreground": "#1e293b",
        "sidebar-primary": "#3b82f6",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#f1f5f9",
        "sidebar-accent-foreground": "#334155",
        "sidebar-border": "#e2e8f0",
      },
      borderRadius: {
        lg: "0.75rem",
        md: "0.5rem",
        sm: "0.25rem",
      },
    },
  },
  plugins: [],
}
